### ISSUE TITLE
06-04 15:33:03.795 16337-16337/wang.imallen.blog.servicemanager E/AndroidRuntime: FATAL EXCEPTION: main Process: wang.imallen.blog.servicemanager, PID: 16337

### ISSUE THREAD

**Issue by snailGoing** [iqiyi/Andromeda#14]
--------- beginning of crash
06-04 15:33:03.795 16337-16337/wang.imallen.blog.servicemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: wang.imallen.blog.servicemanager, PID: 16337
    java.lang.RuntimeException: Unable to destroy activity {wang.imallen.blog.servicemanager/wang.imallen.blog.cherrymodule.CherryActivity}: java.lang.IllegalArgumentException: Service not registered: org.qiyi.video.svg.remote.ConnectionManager$1@2c2667b
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4240)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6174)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:869)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.IllegalArgumentException: Service not registered: org.qiyi.video.svg.remote.ConnectionManager$1@2c2667b
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1333)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1511)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at org.qiyi.video.svg.remote.ConnectionManager.unbindAction(ConnectionManager.java:117)
        at org.qiyi.video.svg.remote.RemoteManager.onDestroy(RemoteManager.java:111)
        at org.qiyi.video.svg.life.ActivityFragLifecycle.onDestroy(ActivityFragLifecycle.java:84)
        at org.qiyi.video.svg.fragment.SupportRemoteManagerFragment.onDestroy(SupportRemoteManagerFragment.java:163)
        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2593)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1557)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3208)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:343)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at android.app.Activity.performDestroy(Activity.java:6868)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258) 
        at android.app.ActivityThread.-wrap6(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6174) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:869) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
06-04 15:33:03.796 16337-16337/wang.imallen.blog.servicemanager D/HprofFactory: Create HprofDebugEx

**Comment by snailGoing** [comment]
pressed back key to finish MainActivity, it happened to crash when had registed local and remote services  .

**Comment by HiWong** [comment]
Thank you for your feedback. I will solve it as soon as possible.

**Comment by snailGoing** [comment]
Besides, using startService() is forbiddened after AndroidO platform,instead of startForegroundServce(). Hence, there will be a notification shown in shade.

**Comment by HiWong** [comment]
Got it! I will try another way to convey data.

**Comment by helang1991** [comment]
都是国人，何必用英文呢，哈哈哈😂

**Comment by HiWong** [comment]
@snailGoing Andromeda Core 1.1.8 the crash involved in unbind action. The reason is that old ServiceConnection hadn't been removed from connectionCache(field of ConnectionManager) after unbind, and the next time it will be reused when it shouldn't be.

**Comment by HiWong** [comment]
@snailGoing You said "Besides, using startService() is forbiddened after AndroidO platform,instead of startForegroundServce(). Hence, there will be a notification shown in shade." But I can't repeat "notification shown in shade" on Nexus 6p(Android 8.1.0). Can you tell me what kind of phone you use?
