### ISSUE TITLE
Andromeda.registerRemoteService(IPushAidlInterface.class, BuyAppleImpl.getInstance());异常

### ISSUE THREAD

**Issue by XiangliJiaxing** [iqiyi/Andromeda#24]
Activity中调用如下：
Andromeda.init(this.getApplication());
        Intent intent = new Intent(this.getApplicationContext(), PushService.class);
        this.getApplicationContext().startService(intent);
PushService的oncreate中
Andromeda.registerRemoteService(IPushAidlInterface.class, BuyAppleImpl.getInstance());

完整的异常堆栈信息如下：
08-15 23:24:33.138 14705-14705/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xljx.push.multiprocessdemo:push, PID: 14705
    java.lang.RuntimeException: Unable to create service com.xljx.lib.PushService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
        at org.qiyi.video.svg.transfer.RemoteTransfer.getIBinderFromProvider(RemoteTransfer.java:158)
        at org.qiyi.video.svg.transfer.RemoteTransfer.initDispatchProxyLocked(RemoteTransfer.java:110)
        at org.qiyi.video.svg.transfer.RemoteTransfer.registerStubService(RemoteTransfer.java:171)
        at org.qiyi.video.svg.Andromeda.registerRemoteService(Andromeda.java:143)
        at com.xljx.lib.PushService.onCreate(PushService.java:16)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
        at android.app.ActivityThread.-wrap4(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by XiangliJiaxing** [comment]
原因是有几个进程，Application就会初始化几次，对应的Andromeda.init(Context);也需要调用相应的次数
