### ISSUE TITLE
能否增加Java 1.8编译支持？

### ISSUE THREAD

**Issue by kylin17** [iqiyi/Andromeda#33]
如题，使用
``` gradle
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
编译报错：
``` java
Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090)
	at javassist.bytecode.ConstPool.read(ConstPool.java:1033)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:149)
	at javassist.bytecode.ClassFile.read(ClassFile.java:737)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:108)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	... 53 more
```

查看plugin项目中，``javassist``使用的版本是``javassist:3.12.1.GA``，``javassist`` **3.18**以下的版本不支持在``JDK1.8``下运行。

**Comment by kylin17** [comment]
#34 I send a pull request to you. Please review the code and test.
